export const brand = 'Northline Business Studio';
export const arrow = '<span aria-hidden="true">↗</span>';
export const mark = '<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M6 26V6L26 26V6M6 16H26" stroke="currentColor" stroke-width="3"/></svg>';
const label = (text) => `<p class="eyebrow"><span></span>${text}</p>`;
const button = (text, page, secondary = false) => `<a class="button${secondary ? ' button-light' : ''}" href="{{url:${page}}}">${text}${arrow}</a>`;
const cta = `<section class="cta-section"><div class="container cta-inner"><div>${label('A little more clarity. A lot more possibility.')}<h2>Make room for<br><em>what’s next.</em></h2></div><div class="cta-side"><p>Tell us where things feel complicated.<br>Let’s find a simpler way forward.</p>${button('Start a conversation', 'contact', true)}</div></div></section>`;
const services = [
 { number:'01', title:'Business operations', slug:'operations', intro:'A clearer way to run the day-to-day.', text:'Bring structure to recurring tasks, team handoffs, and the details that keep your business moving.', items:['Workflow mapping & documentation','Process checklists & SOPs','Project coordination & follow-through'], icon:'<path d="M5 7h14v5H5zM5 17h14v5H5zM12 12v5"/>' },
 { number:'02', title:'Financial organization', slug:'financial', intro:'Your numbers, neatly in order.', text:'Organize records and routine bookkeeping workflows so you can see what needs attention.', items:['Transaction & expense organization','Accounts payable & receivable tracking','Monthly reporting preparation'], icon:'<path d="M5 21V13h4v8M11 21V7h4v14M17 21V3h4v18"/>' },
 { number:'03', title:'Executive & client support', slug:'support', intro:'Thoughtful support, behind the scenes.', text:'Keep schedules, communication, and client details connected without losing the personal touch.', items:['Calendar & inbox coordination','Client onboarding & follow-ups','Meeting notes & action tracking'], icon:'<path d="M4 5h16v12H9l-5 4V5Z"/><path d="M8 9h8M8 13h5"/>' }
];
const serviceCards = services.map(s => `<article class="service-card"><div class="card-top"><svg viewBox="0 0 26 26" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">${s.icon}</svg><span>${s.number}</span></div><h3>${s.title}</h3><p>${s.text}</p><a class="text-link" href="{{url:services}}#${s.slug}">Explore service ${arrow}</a></article>`).join('');
export const pages = {
 home: {title:'A clearer path for your business', description:'Meet Northline, a concept business-support studio. Explore operations, financial organization, and executive support in this website sample.', content:`
<section class="hero container"><div class="hero-copy">${label('Thoughtful support for small businesses')}<h1>Good business.<br>Less busywork.<br><em>More possibility.</em></h1><p class="hero-description">Practical operations, organized finances, and dependable support. We bring clarity to the everyday, so you can focus on the bigger picture.</p><div class="hero-actions">${button('Explore our services','services')}<a class="quiet-link" href="{{url:about}}">Meet Northline <span aria-hidden="true">→</span></a></div><div class="hero-footnote"><span class="small-cross" aria-hidden="true">✳</span><p>Built around your business.<br><strong>Designed to make work feel simpler.</strong></p></div></div><figure class="hero-image"><img src="{{asset}}/workspace.webp" width="1536" height="1024" alt="Sunlit workspace with a walnut desk, navy notebook, and a leafy branch" fetchpriority="high"><figcaption><span class="caption-icon" aria-hidden="true">↗</span><span>A little structure.<br><strong>A fresh perspective.</strong></span></figcaption><span class="image-index">THE NORTHLINE APPROACH / 01</span></figure></section>
<section class="focus-strip"><div class="container focus-inner"><span class="eyebrow">A clear focus</span><span>Organize the details</span><span class="separator" aria-hidden="true">✳</span><span>Connect the moving parts</span><span class="separator" aria-hidden="true">✳</span><span>Move forward with confidence</span></div></section>
<section class="section container"><div class="section-heading"><div>${label('What we do')}<h2>The support behind<br><em>your next step.</em></h2></div><p>Every business has moving parts.<br>We help them work better together.</p></div><div class="service-grid">${serviceCards}</div></section>
<section class="approach-section"><div class="container approach-grid"><div class="approach-art" aria-hidden="true"><span class="art-label">SMALL DETAILS. BIG PICTURE.</span><div class="northline-symbol">${mark}</div><span class="art-bottom">A clear direction<br>starts with a simple plan. <span>↗</span></span></div><div class="approach-copy">${label('How we work')}<h2>Good systems.<br><em>Human connection.</em></h2><p>You know your business. We take the time to understand it. Together, we turn scattered tasks into practical routines that fit the way you work.</p><ol class="process-list"><li><span>01</span><div><h3>Listen first</h3><p>Understand your priorities and where support matters most.</p></div></li><li><span>02</span><div><h3>Build a simple plan</h3><p>Define the next steps, responsibilities, and a rhythm that works.</p></div></li><li><span>03</span><div><h3>Keep things moving</h3><p>Stay connected, follow through, and make room to improve.</p></div></li></ol><a class="text-link" href="{{url:about}}">More about our approach ${arrow}</a></div></div></section>${cta}`},
 about: {title:'About us', description:'Discover the idea behind Northline Business Studio and our practical, people-first approach to small-business support.', content:`
<section class="page-heading container">${label('About Northline')}<h1>A steady hand.<br><em>A clearer direction.</em></h1><p>We believe small businesses deserve thoughtful support, simple systems, and space to do their best work.</p></section>
<section class="container story-grid"><figure class="story-image"><img src="{{asset}}/workspace.webp" width="1536" height="1024" alt="Calm workspace with natural light and a neatly organized desk"><figcaption>A calmer everyday starts with a clearer plan.</figcaption></figure><div class="story-copy">${label('Our story')}<h2>Built for the people<br><em>behind the business.</em></h2><p>Running a small business often means wearing every hat. Between client conversations, paperwork, and daily decisions, the important details can become a lot to carry.</p><p>Northline is built around a simple idea: reliable support should make your working day clearer. We bring care and structure to the work behind the scenes, with practical solutions that fit your business.</p><p>Our approach starts with listening. From there, we organize the details, clarify the next steps, and keep the conversation open.</p><a class="text-link" href="{{url:services}}">Discover how we can help ${arrow}</a></div></section>
<section class="section container"><div class="section-heading"><div>${label('What guides us')}<h2>Small principles.<br><em>Everyday impact.</em></h2></div><p>A few things we keep at the center<br>of the way we work.</p></div><div class="value-grid"><article><span>01 / CLARITY</span><h3>Keep it understandable.</h3><p>Clear priorities, useful documentation, and communication that leaves everyone on the same page.</p></article><article><span>02 / CARE</span><h3>Notice the details.</h3><p>Thoughtful preparation and consistent follow-through, from the first conversation to the last task.</p></article><article><span>03 / COLLABORATION</span><h3>Work together.</h3><p>Build a supportive working relationship and make space for feedback as the business evolves.</p></article></div></section>
<section class="quote-band"><div class="container"><span class="eyebrow">Our guiding idea</span><p>“Make the everyday work better,<br>so the bigger picture can grow.”</p><span class="quote-credit">THE NORTHLINE APPROACH</span></div></section>${cta}`},
 services: {title:'Our services', description:'Explore Northline’s concept services: business operations, financial organization, and executive and client support.', content:`
<section class="page-heading container">${label('Our services')}<h1>Support that fits<br><em>the way you work.</em></h1><p>Start with what needs attention. Build from there. Our support connects the everyday details with your bigger goals.</p><nav class="service-jumps" aria-label="Explore services">${services.map(s=>`<a href="#${s.slug}">${s.title} <span aria-hidden="true">↓</span></a>`).join('')}</nav></section>
<div class="container service-details">${services.map(s=>`<section class="service-detail" id="${s.slug}"><div class="service-number">${s.number}<svg viewBox="0 0 26 26" fill="none" stroke="currentColor" stroke-width="1.2" aria-hidden="true">${s.icon}</svg></div><div><span class="eyebrow">${s.title}</span><h2>${s.intro}</h2><p>${s.text}</p>${button('Let’s talk about your needs','contact')}</div><div class="service-includes"><span class="eyebrow">Where we can help</span><ul>${s.items.map(i=>`<li><span aria-hidden="true">↗</span>${i}</li>`).join('')}</ul></div></section>`).join('')}</div>
<section class="section soft-section"><div class="container faq-grid"><div>${label('A few helpful answers')}<h2>Let’s make<br><em>things clear.</em></h2><p>Have something else in mind?<br><a class="text-link" href="{{url:contact}}">Start a conversation ${arrow}</a></p></div><div class="faq-list"><details open><summary>Can support be tailored to my business?</summary><p>Yes. We start with your priorities, current workflows, and the kind of help you need. The scope can focus on one area or connect several services.</p></details><details><summary>How does a project get started?</summary><p>We begin with a conversation about your business. Next, we agree on the scope, deliverables, communication, and timing before any work starts.</p></details><details><summary>Can we work together remotely?</summary><p>Our concept service model is designed around remote collaboration, shared documents, and regular check-ins. Tools and meeting times are agreed at the start.</p></details><details><summary>Do you provide tax or legal advice?</summary><p>No. Financial organization focuses on records and bookkeeping support. Tax, legal, and regulated advice should come from an appropriately qualified professional.</p></details></div></div></section>${cta}`},
 contact: {title:'Let’s talk', description:'Explore the Northline contact page and demo inquiry form. This concept website does not collect or send messages.', content:`
<section class="page-heading container">${label('Let’s talk')}<h1>A good next step<br><em>starts with hello.</em></h1><p>Tell us a little about your business and where you could use an extra hand.</p></section>
<section class="container contact-grid"><aside class="contact-aside"><div class="contact-card"><span class="eyebrow">A conversation, not a commitment.</span><h2>What’s on<br><em>your mind?</em></h2><p>Whether you need a fresh perspective or help with the day-to-day, the first step is understanding what matters to you.</p><div class="contact-detail"><span class="detail-icon" aria-hidden="true">↗</span><div><strong>Working together, wherever you are.</strong><p>Remote collaboration for small businesses.</p></div></div><div class="contact-detail"><span class="detail-icon" aria-hidden="true">✳</span><div><strong>Useful things to include</strong><p>Your business type, the support you need, and your preferred timing.</p></div></div></div><p class="demo-explainer"><strong>Portfolio demonstration</strong><br>Northline is a fictional business created for this website sample. This form is a preview; no messages are sent or stored.</p></aside><div class="contact-form-wrap"><h2>Start a conversation</h2><p class="form-intro">Explore how a new inquiry would feel.</p><form id="inquiry-form" class="inquiry-form"><div class="form-row"><div class="field"><label for="full-name">Your name <span>(required)</span></label><input id="full-name" name="name" autocomplete="name" placeholder="Alex Morgan" required maxlength="100"></div><div class="field"><label for="email">Email address <span>(required)</span></label><input id="email" name="email" type="email" autocomplete="email" placeholder="alex@example.com" required maxlength="254"></div></div><div class="field"><label for="business">Business name</label><input id="business" name="business" autocomplete="organization" placeholder="Your business or project" maxlength="150"></div><div class="field"><label for="service">What could you use support with? <span>(required)</span></label><select id="service" name="service" required><option value="">Choose a service</option><option>Business operations</option><option>Financial organization</option><option>Executive & client support</option><option>A combination of services</option><option>I’d like to discuss it</option></select></div><div class="field"><label for="message">Tell us a little more <span>(required)</span></label><textarea id="message" name="message" rows="5" placeholder="A little about your business, what you need, and your ideal timing…" required maxlength="2000"></textarea></div><p class="form-note">Demo only. Please use example details to explore the form.</p><button class="button" type="button" id="preview-inquiry">Preview inquiry ${arrow}</button><div class="form-status" id="form-status" role="status" aria-live="polite" tabindex="-1" hidden></div><noscript><p>This preview form needs JavaScript. No messages are sent.</p></noscript></form></div></section>
<section class="section container"><div class="next-steps"><div>${label('What happens next')}<h2>A simple beginning.</h2></div><ol><li><span>01</span><strong>Share your priorities</strong><p>A little context helps shape the conversation.</p></li><li><span>02</span><strong>Explore the fit</strong><p>Discuss the support that would be most useful.</p></li><li><span>03</span><strong>Agree on the plan</strong><p>Set a clear scope and next steps together.</p></li></ol></div></section>`}
};
export const footer = `<footer class="site-footer"><div class="container footer-main"><div><a class="brand" href="{{url:home}}" aria-label="Northline home">${mark}<span>NORTHLINE<small>BUSINESS STUDIO</small></span></a><p>A clearer path for your business.</p></div><nav aria-label="Footer navigation"><a href="{{url:home}}">Home</a><a href="{{url:about}}">About</a><a href="{{url:services}}">Services</a><a href="{{url:contact}}">Contact</a></nav><a class="footer-cta" href="{{url:contact}}">Let’s find your next step. ${arrow}</a></div><div class="container footer-bottom"><p>Northline Business Studio · Concept website</p><p>Portfolio sample by <a href="https://lourivellorejo-coder.github.io/lourivel-portfolio/">Lourivel Lorejo</a></p></div></footer>`;
